//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieSuggestor
{
    using System;
    using System.Collections.Generic;
using System.Xml.Serialization;

    public partial class Movie
    {
        public Movie()
        {
            this.Rating = new HashSet<Rating>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string Release_Date { get; set; }
        [XmlIgnore]
        public string Video_Release_Date { get; set; }
        [XmlIgnore]
        public string IMDBUrl { get; set; }
        [XmlIgnore]
        public bool Unknown { get; set; }
        [XmlIgnore]
        public bool Action { get; set; }
        [XmlIgnore]
        public bool Adventure { get; set; }
        [XmlIgnore]
        public bool Animation { get; set; }
        [XmlIgnore]
        public bool Childrens { get; set; }
        [XmlIgnore]
        public bool Comedy { get; set; }
        [XmlIgnore]
        public bool Crime { get; set; }
        [XmlIgnore]
        public bool Documentary { get; set; }
        [XmlIgnore]
        public bool Drama { get; set; }
        [XmlIgnore]
        public bool Fantasy { get; set; }
        [XmlIgnore]
        public bool Film_Noir { get; set; }
        [XmlIgnore]
        public bool Horror { get; set; }
        [XmlIgnore]
        public bool Musical { get; set; }
        [XmlIgnore]
        public bool Mystery { get; set; }
        [XmlIgnore]
        public bool Romance { get; set; }
        [XmlIgnore]
        public bool Sci_Fi { get; set; }
        [XmlIgnore]
        public bool Thriller { get; set; }
        [XmlIgnore]
        public bool War { get; set; }
        [XmlIgnore]
        public bool Western { get; set; }
        [XmlIgnore]
        public string PosterUrl { get; set; }
        [XmlIgnore]
        public virtual ICollection<Rating> Rating { get; set; }
    }
}
