//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieSuggestor
{
    using System;
    using System.Collections.Generic;
    using System.Xml.Serialization;
    
    public partial class User
    {
        public User()
        {
            this.Rating = new HashSet<Rating>();
        }
    
        public int Id { get; set; }
        public Nullable<int> Age { get; set; }
        public string Gender { get; set; }
        public string Occupation { get; set; }
        public string Zipcode { get; set; }
        [XmlIgnore]
        public virtual ICollection<Rating> Rating { get; set; }
    }
}
