//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieSuggestor
{
    using System;
    using System.Collections.Generic;
using System.Xml.Serialization;
    
    public partial class Rating
    {
        public int UserId { get; set; }
        public int MovieId { get; set; }
        public int Rating1 { get; set; }
        public Nullable<int> Timestamp { get; set; }
    
        [XmlIgnore] // Want this included?
        public virtual Movie Movie { get; set; }
        [XmlIgnore]
        public virtual User User { get; set; }
    }
}
